### ISSUE TITLE
proposal for alerts

### ISSUE THREAD

**Issue by arisAlexis** [franciscop/picnic#100]
Since almost everything is supported out of the box with this framework the only thing I needed to manually code css was alerts for informing the user much similar to bootstrap. would be nice to include them. 

It is a proposal.

**Comment by franciscop** [comment]
(closed by accident)

Totally agree, they are trivial to make, but the amout of work on documenting/testing them is non-trivial and that's why I haven't gotten around it yet. I'm quite busy for the next month, so PR are welcome but I cannot commit to make it myself right now.

**Comment by arisAlexis** [comment]
Wish I could PR but im one of those backend devs struggling with CSS :)

**Comment by franciscop** [comment]
I see, what are you struggling most? If you want to learn I can give you a hand. For instance, I normally start with the latest release in a separated jsfiddle not to overwhelm myself:

> https://jsfiddle.net/mxzqmkmg/

**Comment by Edwardzyc** [comment]
Hi.
Here is my attempt.
https://jsfiddle.net/mxzqmkmg/2/
Thoughts? I really don't like having to specify two classes for the correct color. I'll work on it. I took the colors from the buttons, maybe someone better with colors can figure out the best color codes for this.

**Comment by franciscop** [comment]
That is awesome, thanks @Edwardzyc . When implementing it in scss, probably you want to extend `label` or make `label` extend it since they are really similar.

Also, they look too similar to the buttons (actually it's the same style but 100% width), so maybe you want to follow a bit of bootstrap path:

> https://jsfiddle.net/franciscop/mxzqmkmg/4/

Or just go totally out:

> https://jsfiddle.net/franciscop/mxzqmkmg/5/

**Comment by franciscop** [comment]
@arisAlexis did you see the [labels](http://picnicss.com/documentation#label)? They are not exactly the same as an alert, but to get by meanwhile you can just add them a `marging: 0; display: block;` and they will behave quite similar.

**Comment by sagarkaurav** [comment]
@franciscop i think alerts should be included in picnic its very basic component which we all needs in our projects. And https://jsfiddle.net/mxzqmkmg/2/ is looking really nice.

**Comment by franciscop** [comment]
I have an issue with this though. As you know Picnic is really colorful, but the color remains for the structural/highlighted elements. However the labels are [normally] intended to go within text paragraphs and their readability must be prioritized so I think a subtle color would be much more appropriate.

I think [an implementation like this](https://serverjs.io/documentation/) (after the first code block) would be much better suited for this component:

![alert](https://user-images.githubusercontent.com/2801252/28580225-2f95ee42-715f-11e7-9ca4-9f18c6eca155.png)

**Comment by AxelTheGerman** [comment]
agree with both of you.... it should be in Picnic, and for a background color it needs to be more subtle. 

Played around with the jsfiddle from @sagarkaurav. Lightened the colors, added that left border in the original colors https://jsfiddle.net/rbtw9taz/ - not sure whether we want to rounded corners or not, also the colors I chose need polishing (definitely not a designer)

**Comment by sagarkaurav** [comment]
Who is going to make PR for this feature or should i work on this. :smile:

**Comment by franciscop** [comment]
Hi everyone, sorry life got in the way and I'm unlikely to ever do this. PR are still welcome though 🙂
