### ISSUE TITLE
Toggable Buttons and Tooltips Don't Play Nicely

### ISSUE THREAD

**Issue by arranf** [franciscop/picnic#106]
After clicking on a toggable button the button retains focus and the tooltip isn't dismissed.

**Comment by franciscop** [comment]
This should be because of the `:focus`, I will dig into it as right now the focus is for accesibility (tabbing elements should display the tooltip).

**Comment by franciscop** [comment]
Well it seems I never got around it. Not sure if it's still an issue, but I have other priorities right now. PR still accepted though 🙂
