### ISSUE TITLE
Flex grid not laying out correctly on IOS safari

### ISSUE THREAD

**Issue by TimeBandit** [franciscop/picnic#112]
# Issue

In creating a mobile first layout on a smart phone I am setting up two columns in a container `div`. This then has four child `divs`, each of which should take up half(i.e. one) of the columns on a mobile device. This works as expected in responsive view on Firefox(see image below) but not on the actual device.

![screen shot 2016-08-08 at 15 43 14](https://cloud.githubusercontent.com/assets/2059850/17483701/0546e58c-5d7f-11e6-9a88-e41991ef4d11.png)
# System
## Dev Machine

![screenshot from 2016-08-08 15-46-30](https://cloud.githubusercontent.com/assets/2059850/17483814/7462c68e-5d7f-11e6-9c50-132211cc506a.png)

![screenshot from 2016-08-08 15-48-28](https://cloud.githubusercontent.com/assets/2059850/17483860/957196ac-5d7f-11e6-9f46-af2d00353946.png)
## Iphone

IOS 7.1.2
# Reproduction
1. unzip this -> [picnic_issue.zip](https://github.com/picnicss/picnic/files/407045/picnic_issue.zip) into a folder.
2. `cd` into the folder and run a local HTTP server or if you have Python installed, `python -m SimpleHTTPServer`
3. View the page on localhost:8000 locally.
4. Open Safari on your IPhone and then navigate to `server_internal_IP_adress:8000`.
5. You will observe that the `cards` of the layout only display one column.

**Comment by franciscop** [comment]
I cannot check it right now (will do it later), but did you set the viewport tag? [Don't forget the viewport meta tag](http://webdesign.tutsplus.com/articles/quick-tip-dont-forget-the-viewport-meta-tag--webdesign-5972)

Every single time that it worked differently in Firefox for desktop (responsive view) and an actual mobile for me is because I would forget it.

**Comment by TimeBandit** [comment]
The issue is seen even with the `<meta name="viewport" content="width=device-width, initial-scale=1">` in the `HEAD`

**Comment by TimeBandit** [comment]
Just went back over my original code. I was always using the viewport meta tag when this issue came up in the project code.

**Comment by franciscop** [comment]
I can reproduce this on [browserstack](https://www.browserstack.com/), I will try to fix it but it looks like it is just that it needs the -webkit- (check "Show all" in [caniuse](http://caniuse.com/#feat=flexbox))

**Comment by TimeBandit** [comment]
Is it the only Safari version you saw this on? I decided to use it for a non profit site I’m building but I am still at the early stages, if it doesn’t work with Picnic (which is a great CSS library btw) then I will switch to Materialise. I did run auto-prefixer over you library with no improvement.

**Comment by TimeBandit** [comment]
Let me know if there is anything I can do to help :)

**Comment by franciscop** [comment]
Sorry I never came back to this. It seems like this is for a Safari version 7.1, which should be not an issue anymore. Otherwise please feel free to reopen the issue. Hope it worked out with you, either fixing Picnic or with Materialise.
