### ISSUE TITLE
Removing tabs

### ISSUE THREAD

**Issue by franciscop** [franciscop/picnic#113]
The tabs element is just a super-hack and I don't think it's production-ready at all. For a better tab system, javascript is a much better option. So I am removing it from the next major version, 7.0.0.

**Comment by naasking** [comment]
Perhaps adopt the [tabs from mini.css](https://chalarangelo.github.io/mini.css/tab.html)? They seem to work fairly well.

**Comment by pwFoo** [comment]
Tabs shouldn't be removed. Would be better to optimize or replace it!

**Comment by franciscop** [comment]
The problem is that the HTML is really ugly and fragile, which happens when you try to replace javascript to css at this level. I'd like Picnic CSS to be more of a ready-for-production library rather than an experimental library. For instance, `nav`, `grids`, `buttons` and things related to forms are quite stable and a joy to deal with, while `modal` is somewhat painful and `tabs` is just impossible.

An alternative, similar to `.dropimage`, would be to require a bit of javascript, but I think for this situation it wouldn't be trivial and so it doesn't make sense to include it in Picnic **CSS**.

@naasking tabs work perfectly (indeed they do not have the "fixed height" issue that mini.css has thanks to flexbox), see http://picnicss.com/tests for instance. The issue is not that they work/don't work, the issue is that they are painful to work with and adding another library would not really change this.

**Comment by pwFoo** [comment]
I like Picnic CSS because it's similar to the way I tried to build a custom solution. And I was impressed by the css only tabs and modal solutions.

**Comment by pwFoo** [comment]
@franciscop 
HTML of the used tabs is really ugly because of separated input / label elements from the tab content. Maybe that example could be better?

```
<div class="tabs">
    
   <div class="tab">
       <input type="radio" id="tab-1" name="tab-group-1" checked>
       <label for="tab-1">Tab One</label>
       
       <div class="content">
           stuff
       </div> 
   </div>
    
   <div class="tab">
       <input type="radio" id="tab-2" name="tab-group-1">
       <label for="tab-2">Tab Two</label>
       
       <div class="content">
           stuff
       </div> 
   </div>
    
    <div class="tab">
       <input type="radio" id="tab-3" name="tab-group-1">
       <label for="tab-3">Tab Three</label>
     
       <div class="content">
           stuff
       </div> 
   </div>
    
</div>
```

Tutorial: https://css-tricks.com/functional-css-tabs-revisited/
Demo: https://css-tricks.com/examples/CSSTabs/radio.php

**Comment by pwFoo** [comment]
@franciscop 
What do you think about the target / link method? It's easy to build (modals, tabs, ...), but could get in the way of website anker usage (open / close modal change the current website anker and could change the page possition?).

**Comment by sagarkaurav** [comment]
@franciscop  i am closing this issue. Reopen if you think something need to work on.
