### ISSUE TITLE
Non jquery datepicker that works in the picnic modal?

### ISSUE THREAD

**Issue by nmcgann** [franciscop/picnic#130]
Anyone know of a non-jquery date picker that works properly on form fields in the picnic modal?

I had a quick try with something I have used before (CibulCalendar), but if I attach to the date input field it is only part-shown and the modal contents needs to be scrolled up to see the full calendar. It isn't overlaying on top of the modal, but it is inside the modal window.

Anyone tried Pikaday? I couldn't get that to appear on top of the modal or in it's window at all, it's behind on the overlay wherever I try attaching it.

**Comment by nmcgann** [comment]
This is quite hard to make work, but I have adapted this: https://github.com/remi-grumeau/DatePicker by hacking the CSS and JS (mainly adding a callback called when the picker shows). This is a very simple picker, but it has the advantage that a parameter can be passed to force-override the left/top position that the canvas is drawn at rather than allowing the picker to calculate its own location (which comes out wrong due to the way the modal works).

I set the datepicker canvas to `position:fixed` with it attached to the `<article>` of the modal and then when the picker is visible the absolute offset is calculated to locate it next to the input field in the modal. (top left of the modal `<article>` is 0,0)

There have got to be cleaner ways of making datepickers function in the modal, but I suspect that the way that the modal works may need to be changed first?

**Comment by franciscop** [comment]
Maybe you could try checking/changing the z-index of the modal and/or pikaday? I have never tried anything like this, the modal was originally thought as a really simple message but I can see how many people would want to build a full form in it with datepickers and others.

**Comment by nmcgann** [comment]
I've tried messing with the Z-index and it doesn't help with the location issues, it's the fixed position and transform+scaling that causes the problem I think. I'm not a CSS expert, so I can't exactly work out what is going wrong!

All these datepickers pop up a div with absolute positioning (by default) and then can't locate it correctly relative to an input in the modal.

**Comment by franciscop** [comment]
Sorry but this is too specific to be a priority for me and will probably remain so, so I will just close this issue as it most likely won't be fixed.
