### ISSUE TITLE
grid - flex negative margin

### ISSUE THREAD

**Issue by SharpSeeEr** [franciscop/picnic#135]
@franciscop - on your grid you give .flex a negative margin-left, and .flex > * a padding-left of the same amount.  I've removed both on those on a test page and it appears to still work and line up properly.  But I'm sure you did this for a reason.  

So the question is - why does .flex have negative margin-left and >* a padding-left?

**Comment by franciscop** [comment]
It is an old trick to make the spacing and width consistent and unfortunately it needs to stay. I've spent many many hours debugging it and believe me when I say that. [See this explanation](http://www.helloerik.com/the-subtle-magic-behind-why-the-bootstrap-3-grid-works) for example. The simple example will seem to work without padding (it still doesn't work, compare a 6-column spaces with 3-column spaces which won't line up) but in the complex examples it totally breaks up.

**Comment by SharpSeeEr** [comment]
Thanks for the explanation.  I figured it would be something like that.  I don't have to like it though.  :)
