### ISSUE TITLE
Bug in documentation for Responsive column count example

### ISSUE THREAD

**Issue by Slevinski** [franciscop/picnic#136]
The file web/style/style.min.css is incomplete.  It does not contain "three-600".  This is breaking the documentation in the grid section.  The "Responsive column count" example isn't working for "three-600" because the style isn't defined in web/style/style.min.css.  FYI

**Comment by franciscop** [comment]
I created a specific super-minimal file for a 10kb website competition; I'll revert it to the *normal* build.
