### ISSUE TITLE
Nav documentation incomplete

### ISSUE THREAD

**Issue by naasking** [franciscop/picnic#137]
The documentation should specify that the input element MUST precede the label element for this to work properly. Otherwise it just doesn't work properly:

http://codepen.io/anon/pen/OpVKzy

If you shrink the viewport so the menu collapses, the side menu pops up as expected when you click the burger, but there's no way to dismiss the popup. It only goes away if I refresh the screen. It also doesn't apply an overlay on everything behind the menu like it does on the main site if you don't get the order right.

Of course, allowing the input to be placed inside the label or making the order not matter would also be great.

**Comment by franciscop** [comment]
> Of course, allowing the input to be placed inside the label or making the order not matter would also be great.

Those are not possible due to the way CSS works. You can have a selector for the following elements:

```
input:checked ~ * { ... }
```

However you cannot have a selector for the previous or above elements; and the nav relies on this to hide/show the sidebar in mobile.

Sure, I leave this open for the next build to add a note.

**Comment by franciscop** [comment]
I believe I never added a note. Please feel free to do a PR, but this is very low priority for me right now and very unlikely to change.
