### ISSUE TITLE
Hiding elements at breakpoints

### ISSUE THREAD

**Issue by naasking** [franciscop/picnic#141]
I know you have none-X classes, but these hide elements as the viewport gets larger. I instead want to hide elements as the viewport gets smaller, which these do:

```
@media all and (max-width: 500px) {
    .hide-500 { display: none }
}
@media all and (max-width: 600px) {
    .hide-600 { display: none }
}
@media all and (max-width: 700px) {
    .hide-700 { display: none }
}
@media all and (max-width: 800px) {
    .hide-800 { display: none }
}
...
```
Example uses of the none-X classes in the docs would also be helpful.

**Comment by franciscop** [comment]
The `none-X` feature is supposed to be only for the grid, where I go away from the rest of the library of trying to keep things as semantic as possible. Adding classes like this would have two problems:

- Non-semantic
- Mobile first gets all screwed. It is not just a fashion, as not following it results in buggy behaviour:

```css
@media all and (max-width: 800px) { ... }
@media all and (min-width: 800px) { ... }
```

There's a bug there when it's exactly 800px. The only sane way to avoid it is to *only* use one of `max-width` **or** `min-width` consistently along the code (799px won't work). So I chose `min-width` as it has other benefits.

While it won't be added to the core, maybe you could consider it the other way around:

```css
@media all and (min-width: 800px) {
  .show-500 { display: block; }
}
```

Of course you'd need to choose between `block`, `inline` or `inline-block`, but that's up to you.
