### ISSUE TITLE
Drop menu

### ISSUE THREAD

**Issue by naasking** [franciscop/picnic#142]
A drop menu on hover or click would be handy. This would be particularly useful in conjunction with the nav menu.

**Comment by franciscop** [comment]
It is already implemented in the Issue #55. You can see a demo in here:

**[JSFiddle Demo](https://jsfiddle.net/franciscop/bk9v2mq8/)**

However I won't be adding this to the core of Picnic CSS as the syntax is quite ugly and it could totally benefit with some Javascript (this is one of these situations when a bit of JS would go a long way).
