### ISSUE TITLE
Howto: user tabs with 6 items

### ISSUE THREAD

**Issue by josvenes** [franciscop/picnic#158]
I cant get it right with the tabs
What do i do wrong. Help wanted
Here's my code

div class="flex">
            div class='inhoud'>
                div class="tabs ">
                    input id='tabD-1' type='radio' name='tabgroupD' checked />
                    label class="pseudo toggle" for="tabD-1">I</label>
                    input id='tabD-2' type='radio' name='tabgroupD'>
                    label class="pseudo button toggle" for="tabD-2">P</label>
                    input id='tabD-3' type='radio' name='tabgroupD'>
                    label class="pseudo button toggle" for="tabD-3">D</label>
                    input id='tabD-4' type='radio' name='tabgroupD'>
                    label class="pseudo button toggle" for="tabD-4">C</label>
                    input id='tabD-5' type='radio' name='tabgroupD'>
                    label class="pseudo button toggle" for="tabD-5">A</label>
                    input id='tabD-6' type='radio' name='tabgroupD'>
                    label class="pseudo button toggle" for="tabD-6">B</label>

                    <div class="row">
                        <div class='tabs'>
                            <div>
                                <h2>1 XXXXXXXXXXXXXXXXXXXXX</h2>
                            </div>
                        </div>

                        <div class="tabs">
                            <div>
                                <h2>2 XXXXXXXXXXXXXXXXXXXXX</h2>
                            </div>
                        </div>
                        
                        <div class='tabs'>
                            <div>
                                <h2>3 XXXXXXXXXXXXXXXXXXXXX</h2>
                            </div>
                        </div>

                        <div class="tabs">
                            <div>
                                <h2>4 XXXXXXXXXXXXXXXXXXXXX</h2>
                            </div>
                        </div>
 
                        <div class="tabs">
                            <div>
                                <h2>5 XXXXXXXXXXXXXXXXXXXXX</h2>
                            </div>
                        </div>
                        
                        <div class="tabs">
                            <div>
                                <h2>6 XXXXXXXXXXXXXXXXXXXXX</h2>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

**Comment by franciscop** [comment]
The maximum number of tabs [right now is 4](https://github.com/franciscop/picnic/blob/develop/plugins/tabs/_class.scss#L90). I just saw that it doesn't say it anywhere, but the Tabs is going to be removed for the next major version since it's quite messy and you'd be better off just using Javascript for this.

**Comment by sagarkaurav** [comment]
@franciscop  it think we need to tell people that we are baking new version for picnic css and tell them to see our develop branch what will be changed in new major release. For now we can just add this  to our README file.
