### ISSUE TITLE
Tabs are not accessible

### ISSUE THREAD

**Issue by adrhumphreys** [franciscop/picnic#160]
Tabs currently are not accessible. I'm not sure if you can do pure css tabs that are completely accessible though. We could do something similar to this: https://kyusuf.com/post/completely-css-tabs but that wouldn't completely fix the issue.

What should we do, change it to the above, ignore accessibility, or use some javascript?

**Comment by franciscop** [comment]
How is that more accessible? Tabs are getting removed for a future version, if you have a PR feel free to make it, but otherwise the problem will *fix* on its own given some time.
