### ISSUE TITLE
Multi-line Tooltip

### ISSUE THREAD

**Issue by gregoriochiko** [franciscop/picnic#162]
Hey,
I just wonder if I could create a multi-line text on my tooltip. I've been looked for the documentation about this, but it seems that I can't find it. Maybe you could add some extra feature?

**Comment by franciscop** [comment]
The way that tooltips work now (using CSS pseudo-elements) it is impossible to add them. The alternative is to use Javascript and a more advanced engine, but there are already things like that, I particularly like popper: https://popper.js.org/
