### ISSUE TITLE
select and button elements not aligned horzontally

### ISSUE THREAD

**Issue by dceejay** [franciscop/picnic#163]
Could select and button elements be made to align, and be the same height by default - so that both top and bottom align ?

![image](https://user-images.githubusercontent.com/5375409/32698243-0828d068-c79a-11e7-9eb2-37d88849e4c0.png)

These overrides seem to fix it - but would be nice if they were the default

        select {
            height: 2.2em;
        }
        button {
            vertical-align: baseline;
        }

**Comment by franciscop** [comment]
This seems like it'd do the trick, could you wrap it up into a PR please?
