### ISSUE TITLE
Many issues

### ISSUE THREAD

**Issue by franciscop** [franciscop/picnic#175]
Bug reports: https://github.com/webcompat/web-bugs/issues/16068

My answer:

Wow thanks a lot! Yes, bugs and misalignments have been creeping in steadily over the years, it's great to see the list here!

First I'd have to clean-up the code, Picnic CSS is long overdue for an overhaul in several fronts; but the amount of work required is quite huge, so I've been putting it off and off. I am even using Picnic at work for some smaller components (buttons, grid and such) so even the SCSS would need quite a bit of love as well.

However, right now my priorities are CSS > SCSS > Website. Then, within my projects [server.js](https://serverjs.io/) (the website itself based on picnic) also has higher priority to Picnic, so realistically speaking I won't be able to fix this within the next few months as none of the issues seem life-or-death.

I will ask at my day job about this to see if at least fixing bugs in the libraries we use (including Picnic) would be okay. Again, thanks a lot for the reports :heart:

**Comment by mckaygerhard** [comment]
hi @franciscop could you firts pay attention as 1- priority the documentation for non-experts and novice users to hwo to personalize and build ? if a non-hacker can proper made personalizations can help on you better and provide more contribution!

and please! how to build with less network-online depends

**Comment by franciscop** [comment]
@mckaygerhard do not open more issues telling me what to do, and avoid using exclamations when commenting on Github
