### ISSUE TITLE
Grid demo not working as described

### ISSUE THREAD

**Issue by skylogic004** [franciscop/picnic#177]
On the Picnic documentation page, there's a section titled "Responsive column count" with a demo grid that should have 3 columns when screen size is between 600px and 1200px. I tried this and it doesn't appear to be working (I get 6 columns above 1200px and 2 columns everywhere else).

Screenshot below:
![picnic_grid_bug](https://user-images.githubusercontent.com/4992373/40511622-228a5726-5f55-11e8-9f31-ca80d1e32f7b.png)

I've never used Picnic CSS before, just reading the documentation for the first time and discovered this issue. I'm assuming it's a bug rather than me not reading the description properly - do let me know if I've assumed incorrectly.

**Comment by franciscop** [comment]
Note: give it a bit so the CDN updates.

**Comment by franciscop** [comment]
![fixed](https://user-images.githubusercontent.com/2801252/40521449-aafc432e-6006-11e8-919c-089e35e26f0a.png)
