### ISSUE TITLE
dont show empty label

### ISSUE THREAD

**Issue by srfirouzi** [franciscop/picnic#182]
hello
please add this code for don't show empty label.
unfortunately, i don't know SCSS

.label:empty{
	display: none;	
}

**Comment by franciscop** [comment]
I am sorry but this is not a good feature for CSS, where you are setting the label you should avoid setting it if there is no text instead.

**Comment by srfirouzi** [comment]
hello
in automatic system like cms , if label exist ,must show .if not ,must hide it 
by this option , in dynamic update by ajax ,don't need hide label by js
