### ISSUE TITLE
problem in table in card

### ISSUE THREAD

**Issue by srfirouzi** [franciscop/picnic#183]
hello
if use table in card by style="width=100%" ,this don't work , i check it, problem in 

.card > *, .modal .overlay ~ * > * {
    max-width: 100%;
  display: block;
}
must be display for table is "table"

**Comment by franciscop** [comment]
It would be `style="width: 100%"` (`:` instead of `=`) but that's a separated issue.

You could wrap the table with a div then to avoid the direct child selector.

**Comment by srfirouzi** [comment]
hello
this is a error in typing :) , i resolve it by
style="width: 100%;display: table;"
