### ISSUE TITLE
Allow "<select size=10>"

### ISSUE THREAD

**Issue by doublex** [franciscop/picnic#187]
Replace CSS:
````
select { ... }
````
->
````
select:not([size]) { ... }
````

**Comment by franciscop** [comment]
Any explanation behind this?

**Comment by franciscop** [comment]
I didn't know about that HTML feature, thanks! However `select:not([size])` is a no-go since it blows up the specificity and makes life harder for everyone...

I think then the attribute `size` won't be supported out of the box, so that if you want to use it you can add a bit of userland CSS.
