### ISSUE TITLE
how to build an personalized version

### ISSUE THREAD

**Issue by mckaygerhard** [franciscop/picnic#191]
i read carefully #154 #189 #139  #172 and #190

of course was made by people that already know coding.. but also lack of time for contributing (as i see i do not see any pull request by thems)

so if you write docs about how to build i can improve that docs and other peoples with many more time but lack of knowlede can contribute.. 

and i means (and will be sound rare) who to build a minified and unminified css file directly from your repository.. with inclded tml test page example to see

**Comment by franciscop** [comment]
This library is not too beginner-friendly, and TBH it probably will never be. Please feel free to do follow one of these:
- use the default styles
- customize the theme with plain CSS
- hack things together with SCSS. Not part of the official API and no docs provided
- create a PR improving the documentation

**Comment by mckaygerhard** [comment]
hi i never receive that message! .. @franciscop i already know that are not user-friendly so i need directions.. due i not see any developer readme in the git proyect.. 

i already have my hacks in the css, already have my customizations.. now translated to scss... 
it's a scss build but i try with mixed efect .. i cannot remenber .. but now that i'm in short of tuime i need tips to! i'm particular i really need the pull request #184 merged! and some other that sometimes i have..
