### ISSUE TITLE
Documentation is not available

### ISSUE THREAD

**Issue by afgorbunov** [franciscop/picnic#193]
At https://picnicss.com/documentation/ I see 404 page

**Comment by franciscop** [comment]
Nothing has been changed in few months and this was working earlier this week...

The file itself is there:
https://github.com/franciscop/picnic/blob/master/documentation.html

I wonder whether Github Pages changed the way a page is resolved? Let me contact them, and sorry for the trouble...

**Comment by franciscop** [comment]
Oh wait, try without the last slash:

https://picnicss.com/documentation

There should be some config somewhere to allow me fixing it on my end then...

**Comment by afgorbunov** [comment]
Thank you! Now everything works.
