### ISSUE TITLE
Help w/ CSS

### ISSUE THREAD

**Issue by cliffordh** [franciscop/picnic#195]
Trying to move away from Bootstrap and so far liking Picnic. I am trying to implement a Navbar with the following functionality:
Logo and Brand on the left, dropdown menu on the right. No responsive collapse necessary as the menu will always be in a "mobile friendly" state because of the dropdown.. I've got the logo and brand looking good but I'm at a loss on the right side dropdown. Note, there is a profile image that I'm fussing with and trying to get the alignment right... but also, not sure how to get the dropdown to work:

``My Site [img].........................................................................................[username][img] v`
`.................................................................................................................Profile`
`................................................................................................................-------------------`
`................................................................................................................Signout`
`

Above ASCII art version of what I'm trying to accomplish. The username+img and dropdown arrow (indicated by the v) are what I'm going for. Dots for spacing...

**Comment by franciscop** [comment]
There's no dropdown in Picnic unless you refer to [`<select>`](https://picnicss.com/documentation#select), but that's not really a dropdown so you'll either have to use a 3rd party dropdown, write your own or [use something like this](https://github.com/franciscop/picnic/issues/55).
