### ISSUE TITLE
Support for <select multiple> ?

### ISSUE THREAD

**Issue by edent** [franciscop/picnic#197]
The `<select>` element has an optional attribute `multiple` - this allows a user to select more than one option from a dropdown.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#Attributes

Picnic doesn't support this. When `multiple` is added, it is impossible to select any item from the list.

**Comment by franciscop** [comment]
Yes, from early experiments this was an issue... unfortunately I didn't find a solution back then, so very sadly `<select>` with `multiple` is not supported 😢

PR fixing this are very welcome, but beware, from my early experiments it seems it might not be possible.

**Comment by franciscop** [comment]
Hi @edent, `<select multiple>` is now supported thanks to the PR from @kensnyder 🎉

It should be available on version `picnic@6.5.1`, see the test here: https://picnicss.com/tests#select

**Comment by mckaygerhard** [comment]
i'm glad to read that @franciscop  please can you explain me that i need in issue #191 so more people can help to you? as just @edent  do it!?

i have a problem not with lavels and select positions in issue #199
