### ISSUE TITLE
Navbar with fixed width

### ISSUE THREAD

**Issue by hermesramos** [franciscop/picnic#198]
Hello,

I am trying to center icons of the a navbar inside the red box, shown in the image bellow.

![1](https://user-images.githubusercontent.com/11175800/62257078-37af7980-b3da-11e9-9482-2e2866a01ee2.png)

When I create a centered div, with a max-width, inside the nav element, the layout breaks. The burger menu disappears. Please, check ou the code bellow.

        <nav style="background-color: black">
            **<div style="max-width: 980px; margin-left: auto; margin-right: auto">**
            <a href="/" class="brand">              
                <amp-img src="/img/logo.svg" width="20" height="20"></amp-img>
                <span>Brand</span>
            </a>
            
            <input id="bmenub" type="checkbox" class="show">
            <label for="bmenub" class="burger pseudo button"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="block"><path fill="none" d="M0 0h24v24H0z"></path><path fill="currentColor" d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z"></path></svg></label>
            
            <div class="menu">
                <a href="#" class="pseudo button">Demo</a>
                <a href="#" class="button">Plugins</a>
            </div>
            </div>
        </nav>`

![image](https://user-images.githubusercontent.com/11175800/62257146-79402480-b3da-11e9-9a3e-95fe77508e6a.png)

Can you please help me out? 
Thanks

**Comment by franciscop** [comment]
Hey I've done this few times, it's a bit hacky but it works very well:

```js
/* For max-width = 1200px, use half of it: */
nav {
  padding: 0 calc(50vw - 600px);
}
```

**Comment by franciscop** [comment]
A more advanced example that keeps 20px padding around the sides:

```scss
/* max-width = 1200px */
nav {
  padding: 0 20px;

  @media (min-width: 1240px) {
    padding: 0 calc(50vw - 600px + 20px);
  }
}
```
