### ISSUE TITLE
Toggle menu button hidding

### ISSUE THREAD

**Issue by MrGlasspoole** [franciscop/picnic#201]
I can't find out how the menu button is hidden.
On your documentation page if I hide the menu I can see for a half second that the button is
coming from the top?

I made a hamburger with span's and the problem is that the burger is not hidden when the menu is open:
https://test.skulltronics.net/skulltronics/picnic/

Also the brand should have a z-index 1.
If the brand is bigger than the bmenub input is over it and there is a dead area for clicking the brand.

It also would be nice if the scrolling would be disabled if the menu is open.

**Comment by MrGlasspoole** [comment]
Nevermind. I will use another menu.

**Comment by franciscop** [comment]
Sure, thanks for trying picnic

**Comment by MrGlasspoole** [comment]
No reason to be confused :-)

What i wanted was not possible with your menu because i need to mix it with a dropdown.
And after playing around i found out that a sidebar does not look good with this design.
Everybody has a sidebar anyways - that's boring :-)

So i made it a modal for small screens.
You can see it if you go bellow 665px:
https://test.skulltronics.net/skulltronics/picnic/index.html

I also want it lightweight (no jQuery) and use:
https://thednp.github.io/bootstrap.native/index.html#components

So i mix a little bit Bootstrap CSS into picnic.
