### ISSUE TITLE
Example layouts

### ISSUE THREAD

**Issue by kunkinkan** [franciscop/picnic#68]
Some example layouts would be nice.

Similar to concise; http://concisecss.com/documentation/

**Comment by franciscop** [comment]
That example looks perfect, I am doing [an important migration](https://github.com/picnicss/picnic/issues/62) to do first which kind of block anything like this, but I'll add it for sure afterwards. Also I'm changing countries so I won't be able to do it until 1-2 weeks later

**Comment by franciscop** [comment]
If anyone wants to implement some layouts please do so. I don't really have time now.

**Comment by haishanh** [comment]
Hi @franciscop, how do you manage your html files in [picnicss/picnicss.github.io](https://github.com/picnicss/picnicss.github.io)? You edit and write them by hand? It is a lot of pain to edit them when I'm think about trying to solve this "example layouts" issue.

If I rewrite them in [pug][pug] templates and send you a pull request, do you think if it is OK for you? It will make future editing way easier.

I can create a repo and give you a demo, if you are interested.

[pug]: https://github.com/pugjs/pug

**Comment by franciscop** [comment]
Please no, don't rewrite jade in jade (renamed pug)

Take a look inside the folder `web`, they are built with `grunt` before being pushed to github. Only the files that finish in `.html.jade` will get converted to `.html`, while `layout.jade` is just a partial layout. Not though, by layout this means it is the base of the other files, not the layout we are discussing on this issue.

**Comment by haishanh** [comment]
Oops, my bad. I was commenting before inspecting your repo tree carefully, you are absolutely right.

**Comment by franciscop** [comment]
No problem, do you want to create any layout? You can rename the current `layout.jade` to avoid confussion of course

**Comment by haishanh** [comment]
I will give it a try if I have time, not committed :)

Besides this specific issue, I think you'd better also commit the file `../temp/readme.md` (main content of the documentation page), no?

**Comment by franciscop** [comment]
That is odd, I don't remember [doing this change](https://github.com/picnicss/picnic/commit/c4798e09220d2480544e163a05e720c400bbf58d) to use `../temp/readme.md`, it should include `../readme.md` instead. But I guess it's because of `'temp/readme.md': ['src/readme.md', 'src/plugins/**/readme.md']` in the Gruntfile. However, that readme is built dynamically, so it shouldn't be much of an issue anyway.
