### ISSUE TITLE
Nav link on mobile

### ISSUE THREAD

**Issue by franciscop** [franciscop/picnic#76]
From [a tweet](https://twitter.com/tysonmaly/status/702590899507822592):

> @FPresencia I was just trying out the nav for picnicss under documentation on mobile chrome, clicking menu does not work right

**Comment by tvmaly** [comment]
I the problem can be reproduced on desktop Chrome emulating an iphone 6.  I also tested it on a Nexus 5 running Android 4.4 with the latest mobile Chome.  The collapsed menu when it is clicked, just disappears.  No transition appears showing the menu.

**Comment by franciscop** [comment]
Thanks, I'll check into it

**Comment by franciscop** [comment]
Is this still an issue? Could you show an example? I have tested it with browserstack on both of those platforms and it seems to be working.

**Comment by tvmaly** [comment]
Yes, it is still a problem.  If you use the developer tools in Chrome browser and emulate iphone 6 you can still see the issue.

**Comment by franciscop** [comment]
I can reproduce this but I have no idea why it's happening. It has to do with the `float: right` for the burger menu.

**Comment by IbrahimButt** [comment]
@franciscop I emulated an iPhone 6 on Google Chrome for Desktop and the Documentation menu button is working. Am I missing something or should this issue be closed?

**Comment by sagarkaurav** [comment]
I tested menu on google chrome(Samsung mobile) and its working fine. I think this issue should be closed. @franciscop
