### ISSUE TITLE
Modal too high

### ISSUE THREAD

**Issue by franciscop** [franciscop/picnic#94]
When the modal is too high, the scroll becomes awkward. Fix it.

**Comment by Edwardzyc** [comment]
Can you share a screenshot and not phrase it with such rudeness next time

**Comment by Edwardzyc** [comment]
Can you share a screenshot

EDIT: realized this was a to-do and not a random developer

**Comment by franciscop** [comment]
Yep, still should explain it better. When the modal is too tall, the content gets hidden, which is probably not desired. Before it was scrolled but the header (including the title and the "X") were hidden on scroll, which is also not desired:

![mit](https://cloud.githubusercontent.com/assets/2801252/15896183/7c74795a-2d8f-11e6-981f-6ecc53588dd4.png)

**Comment by Edwardzyc** [comment]
Hey - if you have a moment to reproduce this exactly in a fiddle - I'll take a stab at it

**Comment by franciscop** [comment]
I'm thinking about redesigning it from the ground up internally, but I'd need to do some tinkering. For instance, we could fix the header title so then the rest can just scroll. But this has problems on its own (overflow, different font size, etc).

**Comment by franciscop** [comment]
I fixed this at some point :man_shrugging:
